# Generated by Django 5.2.8 on 2025-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
    ]
