# Generated by Django 5.2.8 on 2025-11-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conj', models.CharField(max_length=10)),
                ('conjunto', models.CharField(max_length=10)),
                ('contrato', models.CharField(max_length=20)),
                ('conjseg', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('nomeseg', models.CharField(max_length=100)),
                ('qtd_mut', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('compl', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('codimovel', models.CharField(max_length=10)),
                ('conjunto', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mutuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('codimovel', models.CharField(max_length=20)),
                ('conjunto', models.CharField(max_length=10)),
                ('conjseg', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('ident', models.CharField(max_length=20)),
                ('orgao', models.CharField(max_length=20)),
                ('dtnasc', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('renda', models.FloatField(null=True)),
                ('crenda', models.FloatField(null=True)),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('compl', models.CharField(max_length=50)),
                ('tipoimovel', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
