# Generated by Django 5.2.8 on 2025-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_conjuntohabitacional_endereco_movimentacao_mutuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
