# Generated by Django 5.2.8 on 2025-11-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_movimentacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='mutuario_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_mutuario', to='principal.mutuario'),
        ),
        migrations.AddField(
            model_name='mutuario',
            name='conjunto_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutuarios_conjunto', to='principal.conjuntohabitacional'),
        ),
        migrations.AddField(
            model_name='mutuario',
            name='endereco_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutuarios_endereco', to='principal.endereco'),
        ),
    ]
