# Generated by Django 5.2.8 on 2025-11-24 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_movimentacao_mutuario_fk_mutuario_conjunto_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('conjunto', models.CharField(blank=True, max_length=10)),
                ('chave', models.CharField(blank=True, max_length=50)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('sinal', models.CharField(blank=True, max_length=50)),
                ('conversor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmens', models.IntegerField()),
                ('dtvenc', models.DateField(blank=True, null=True)),
                ('dtpgto', models.DateField(blank=True, null=True)),
                ('juros', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amort', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('seguro', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tca', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fcvs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('em', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rp', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cm', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sddev', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('vlautent', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('sinal', models.CharField(blank=True, max_length=50)),
                ('chave', models.CharField(blank=True, max_length=100)),
                ('conversor', models.FloatField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='principal.contrato')),
            ],
            options={
                'unique_together': {('contrato', 'nmens')},
            },
        ),
    ]
