# Generated by Django 5.2.8 on 2025-11-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_add_telefone_email_mutuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ocorrencia',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
