# Generated by Django 6.0.1 on 2026-01-23 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_contrato_ocorrencia_parcelacontrato_sddev_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelacontrato',
            name='sddev_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.CreateModel(
            name='ValidacaoAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arquivo', models.CharField(choices=[('FH1', 'Arquivo FH1 - Habilitação'), ('RCV', 'Arquivo RCV - Comprovação')], max_length=10)),
                ('data_validacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('ERRO', 'Erro na validação')], max_length=20)),
                ('relatorio_completo', models.TextField()),
                ('erros_encontrados', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('tempo_execucao', models.FloatField(blank=True, null=True)),
                ('tamanho_arquivo', models.IntegerField(blank=True, null=True)),
                ('agentes_utilizados', models.CharField(blank=True, max_length=200)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_ai', to='principal.contrato')),
            ],
            options={
                'verbose_name': 'Validação AI',
                'verbose_name_plural': 'Validações AI',
                'ordering': ['-data_validacao'],
            },
        ),
    ]
