# Generated by Django 6.0.1 on 2026-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_parcelacontrato_sddev_original_validacaoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacaoai',
            name='correcao_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validacaoai',
            name='correcoes_aplicadas',
            field=models.TextField(blank=True),
        ),
    ]
