# Generated by Django 5.2.8 on 2026-01-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_validacaoai_correcao_automatica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprendizadoAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('tipo_erro', models.CharField(max_length=100)),
                ('ocorrencias', models.IntegerField(default=1)),
                ('causa_raiz', models.TextField()),
                ('sugestao_codigo', models.TextField()),
                ('prevencao', models.TextField()),
                ('implementado', models.BooleanField(default=False)),
                ('data_implementacao', models.DateTimeField(blank=True, null=True)),
                ('arquivo_afetado', models.CharField(blank=True, max_length=200)),
                ('prioridade', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Aprendizado AI',
                'verbose_name_plural': 'Aprendizados AI',
                'ordering': ['-prioridade', '-ocorrencias', '-data_analise'],
            },
        ),
    ]
