# Generated by Django 5.2.8 on 2026-01-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_aprendizadoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendizadoai',
            name='arquivo_modificado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aprendizadoai',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendizadoai',
            name='linha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
