# Generated by Django 5.2.8 on 2026-01-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_aprendizadoai_arquivo_modificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_envio', models.CharField(choices=[('FH1', 'FH1 - Ficha de Habilitação'), ('RCV', 'RCV - Registro de Comprovação'), ('DOSSIE', 'Dossiê Digitalizado'), ('CADMUT', 'Cadastro de Mutuário'), ('COMPLEMENTAR', 'Documentação Complementar')], max_length=20)),
                ('frequencia', models.CharField(choices=[('UNICO', 'Envio Único'), ('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], default='UNICO', max_length=20)),
                ('filtros_contratos', models.TextField(blank=True, help_text='JSON com filtros para selecionar contratos')),
                ('proxima_execucao', models.DateTimeField()),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('total_envios', models.IntegerField(default=0)),
                ('envios_sucesso', models.IntegerField(default=0)),
                ('envios_erro', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Agendamento de Envio',
                'verbose_name_plural': 'Agendamentos de Envios',
                'ordering': ['proxima_execucao'],
            },
        ),
        migrations.CreateModel(
            name='CredencialCEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('senha_criptografada', models.CharField(max_length=256)),
                ('matricula_agente', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Credencial CEF',
                'verbose_name_plural': 'Credenciais CEF',
            },
        ),
        migrations.CreateModel(
            name='EnvioCEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(choices=[('FH1', 'FH1 - Ficha de Habilitação'), ('RCV', 'RCV - Registro de Comprovação'), ('DOSSIE', 'Dossiê Digitalizado'), ('CADMUT', 'Cadastro de Mutuário'), ('COMPLEMENTAR', 'Documentação Complementar')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', '⏳ Pendente'), ('PROCESSANDO', '🔄 Processando'), ('ENVIADO', '✅ Enviado'), ('ERRO', '❌ Erro'), ('RETORNO_RECEBIDO', '📥 Retorno Recebido')], default='PENDENTE', max_length=20)),
                ('arquivo_enviado', models.CharField(max_length=500)),
                ('tamanho_bytes', models.IntegerField(default=0)),
                ('hash_arquivo', models.CharField(blank=True, max_length=64)),
                ('protocolo_cef', models.CharField(blank=True, max_length=100)),
                ('codigo_contrato_cef', models.CharField(blank=True, max_length=50)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('log_envio', models.TextField(blank=True)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('enviado_automaticamente', models.BooleanField(default=False)),
                ('tentativas', models.IntegerField(default=0)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cef', to='principal.contrato')),
            ],
            options={
                'verbose_name': 'Envio CEF',
                'verbose_name_plural': 'Envios CEF',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('LOGIN', '🔐 Login'), ('ENVIO', '📤 Envio'), ('DOWNLOAD', '📥 Download'), ('LOGOUT', '👋 Logout'), ('ERRO', '❌ Erro')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('duracao_segundos', models.FloatField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('screenshot', models.CharField(blank=True, max_length=500)),
                ('traceback', models.TextField(blank=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='principal.agendamentoenvio')),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='principal.enviocef')),
            ],
            options={
                'verbose_name': 'Log de Automação',
                'verbose_name_plural': 'Logs de Automação',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RetornoCEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_retorno', models.CharField(choices=[('APROVADO', '✅ Aprovado'), ('REJEITADO', '❌ Rejeitado'), ('PENDENTE', '⏳ Pendente Análise'), ('COMPLEMENTAR', '📋 Documentação Complementar'), ('OFICIO', '📨 Ofício/Comunicado')], max_length=20)),
                ('protocolo', models.CharField(max_length=100)),
                ('arquivo_retorno', models.CharField(blank=True, max_length=500)),
                ('conteudo', models.TextField(blank=True)),
                ('analise_cef', models.TextField(blank=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('documentos_solicitados', models.TextField(blank=True)),
                ('data_retorno', models.DateTimeField()),
                ('data_processamento_local', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('lido', models.BooleanField(default=False)),
                ('requer_acao', models.BooleanField(default=False)),
                ('processado', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retornos_cef', to='principal.contrato')),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retornos', to='principal.enviocef')),
            ],
            options={
                'verbose_name': 'Retorno CEF',
                'verbose_name_plural': 'Retornos CEF',
                'ordering': ['-data_retorno'],
            },
        ),
    ]
