# Generated by Django 6.0.1 on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_agendamentoenvio_credencialcef_enviocef_logautomacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemessaCEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_envio', models.CharField(choices=[('FH1', 'FH1 - Ficha de Habilitação'), ('RCV', 'RCV - Registro de Comprovação'), ('DOSSIE', 'Dossiê Digitalizado'), ('CADMUT', 'Cadastro de Mutuário'), ('COMPLEMENTAR', 'Documentação Complementar')], default='FH1', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', '⏳ Pendente'), ('PROCESSANDO', '🔄 Processando'), ('ENVIADO', '✅ Enviado'), ('ERRO', '❌ Erro')], default='PENDENTE', max_length=20)),
                ('numero_lote', models.CharField(blank=True, max_length=10)),
                ('matricula_agente', models.CharField(blank=True, max_length=20)),
                ('protocolo_cef', models.CharField(blank=True, max_length=100)),
                ('total_contratos', models.IntegerField(default=0)),
                ('total_fichas', models.IntegerField(default=0)),
                ('envios_sucesso', models.IntegerField(default=0)),
                ('envios_erro', models.IntegerField(default=0)),
                ('arquivo_header', models.CharField(blank=True, max_length=500)),
                ('arquivo_dados', models.CharField(blank=True, max_length=500)),
                ('log_processamento', models.TextField(blank=True)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Remessa CEF',
                'verbose_name_plural': 'Remessas CEF',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='enviocef',
            name='status',
            field=models.CharField(choices=[('GERADO', '📦 Gerado'), ('PENDENTE', '⏳ Pendente'), ('PROCESSANDO', '🔄 Processando'), ('ENVIADO', '✅ Enviado'), ('ERRO', '❌ Erro'), ('RETORNO_RECEBIDO', '📥 Retorno Recebido')], default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='enviocef',
            name='remessa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='principal.remessacef'),
        ),
    ]
