# Generated by Django 6.0.1 on 2026-03-25 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_remessacef_enviocef_remessa_and_status_gerado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('tipo_contato', models.CharField(choices=[('TELEFONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('PRESENCIAL', 'Presencial'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('assunto', models.CharField(max_length=150)),
                ('observacoes', models.TextField()),
                ('acordo_novo', models.TextField(blank=True, default='')),
                ('proximo_passo', models.TextField(blank=True, default='')),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluido')], default='ABERTO', max_length=20)),
                ('responsavel', models.CharField(blank=True, default='', max_length=100)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_crm', to='principal.contrato')),
            ],
            options={
                'verbose_name': 'Atendimento CRM',
                'verbose_name_plural': 'Atendimentos CRM',
                'ordering': ['-data_atendimento'],
            },
        ),
    ]
