# Generated by Django 5.2.8 on 2026-04-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_alter_agendamentoenvio_tipo_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='prestacao_inicial',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vlfinanc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vlprop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='agendamentoenvio',
            name='tipo_envio',
            field=models.CharField(choices=[('FH1', 'FH1 - Ficha de Habilitação'), ('RNV', 'RNV - Relação de Não Validados'), ('RCV', 'RCV - Registro de Comprovação'), ('DOSSIE', 'Dossiê Digitalizado'), ('CADMUT', 'Cadastro de Mutuário'), ('DEFESA_REV', 'Defesa de Reversibilidade'), ('COMPLEMENTAR', 'Documentação Complementar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enviocef',
            name='tipo_envio',
            field=models.CharField(choices=[('FH1', 'FH1 - Ficha de Habilitação'), ('RNV', 'RNV - Relação de Não Validados'), ('RCV', 'RCV - Registro de Comprovação'), ('DOSSIE', 'Dossiê Digitalizado'), ('CADMUT', 'Cadastro de Mutuário'), ('DEFESA_REV', 'Defesa de Reversibilidade'), ('COMPLEMENTAR', 'Documentação Complementar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='remessacef',
            name='tipo_envio',
            field=models.CharField(choices=[('FH1', 'FH1 - Ficha de Habilitação'), ('RNV', 'RNV - Relação de Não Validados'), ('RCV', 'RCV - Registro de Comprovação'), ('DOSSIE', 'Dossiê Digitalizado'), ('CADMUT', 'Cadastro de Mutuário'), ('DEFESA_REV', 'Defesa de Reversibilidade'), ('COMPLEMENTAR', 'Documentação Complementar')], default='FH1', max_length=20),
        ),
    ]
