# Generated by Django 5.2.8 on 2026-05-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_add_vlfinanc_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIALLY_REVIEWED', 'Parcialmente Revisado'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('auto_count', models.IntegerField(default=0)),
                ('revisar_count', models.IntegerField(default=0)),
                ('faltando_criticos', models.TextField(blank=True, default='')),
                ('faltando_importantes', models.TextField(blank=True, default='')),
                ('recuperados', models.TextField(blank=True, default='')),
                ('pdf_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_review_queues', to='principal.contrato')),
            ],
            options={
                'verbose_name': 'OCR Review Queue',
                'verbose_name_plural': 'OCR Review Queues',
                'ordering': ['-extraction_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value_extracted', models.TextField(blank=True)),
                ('value_approved', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AUTO_APPROVED', 'Auto-Aprovado'), ('PENDING_REVIEW', 'Aguardando Revisão'), ('USER_CORRECTED', 'Corrigido pelo Usuário'), ('REJECTED', 'Rejeitado')], default='PENDING_REVIEW', max_length=20)),
                ('confidence_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(blank=True, max_length=50)),
                ('review_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='principal.ocrreviewqueue')),
            ],
            options={
                'verbose_name': 'Review Queue Item',
                'verbose_name_plural': 'Review Queue Items',
                'ordering': ['status', '-confidence_score', 'field_name'],
                'unique_together': {('review_queue', 'field_name')},
            },
        ),
    ]
